global_options:
  dart_mappable_builder:
    options:
      renameMethods:
        fromJson: fromJsonString
        toJson: toJsonString
        fromMap: fromJson
        toMap: toJson
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true