name: freight_tracking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  drift: ^2.17.0
  path: ^1.9.0
  path_provider: ^2.0.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  drift_dev: ^2.17.0
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true